apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-pss-baseline
  annotations:
    policies.kyverno.io/title: Enforce Pod Security Standards - Baseline
    policies.kyverno.io/category: Pod Security
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Enforces the Kubernetes Pod Security Standards Baseline profile.
      Maps to CIS 5.2.x, NIST 800-53 SC-7, SOC 2 CC6.1, ISO 27001 A.12.4.1
spec:
  validationFailureAction: Enforce   # change to Audit later if you want
  background: false
  rules:
  # 1.1 HostProcess - Windows pods cannot run as HostProcess
  - name: restrict-hostprocess
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: "Windows HostProcess pods are disallowed (Baseline)"
      pattern:
        =(securityContext):
          =(windowsOptions):
            X(hostProcess): false

  # 1.2 Host Namespaces - sharing host namespaces is disallowed
  - name: restrict-host-namespaces
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: "Sharing host namespaces (IPC, Network, PID) is disallowed"
      pattern:
        spec:
          X(hostIPC): false
          X(hostNetwork): false
          X(hostPID): false

  # 1.3 Privileged Containers
  - name: restrict-privileged
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: "Privileged containers are disallowed"
      pattern:
        spec:
          containers:
          - securityContext:
              privileged: false
          securityContext:
            privileged: false

  # 1.4 Capabilities - disallow dangerous capabilities
  - name: restrict-capabilities
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: "Adding capabilities beyond the default set is disallowed"
      anyPattern:
      - spec:
          containers:
          - securityContext:
              capabilities:
                X(add): "?*"
      - spec:
          =(initContainers):
          - securityContext:
              capabilities:
                X(add): "?*"

  # 1.5 HostPath volumes - restrict to ReadOnlyMany + common safe paths
  - name: restrict-hostpath
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: "HostPath volumes must be read-only and limited to safe paths"
      pattern:
        spec:
          volumes:
          - hostPath:
              path: "/var/run/docker.sock|/var/run/cri-dockerd.sock|/var/lib/docker|/var/lib/kubelet"
              type: DirectoryOrCreate
          OR:
            type: ReadOnlyMany
