apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-ifnotpresent
spec:
  validationFailureAction: Audit
  background: true
  rules:
  - name: containers
    match:
      any:
      - resources:
          kinds:
          - Pod
    mutate:
      foreach:
      - list: "request.object.spec.containers[]"
        patchStrategicMerge:
          element:
            imagePullPolicy: IfNotPresent
            =(resources):
              requests:
                cpu: "100m"
                memory: "128Mi"
              limits:
                cpu: "500m"
                memory: "256Mi"
  - name: initcontainers
    match:
      any:
      - resources:
          kinds:
          - Pod
    mutate:
      foreach:
      - list: "request.object.spec.initContainers[]"
        patchStrategicMerge:
          element:
            imagePullPolicy: IfNotPresent
            =(resources):
              requests:
                cpu: "100m"
                memory: "128Mi"
              limits:
                cpu: "500m"
                memory: "256Mi"
